name: expense_tracker
description: Expense Tracker App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.3.0
  injectable: ^2.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.5
  drift_dev: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
